server:
  port: 8080
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    root: INFO
    co.com.pragma: INFO
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
aws:
  region: ${AWS_REGION}